name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ssl_public_key_pinning, ssl_public_key_pinning_http, ssl_public_key_pinning_dio]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
        working-directory: packages/${{ matrix.package }}
      - run: dart format --output=none --set-exit-if-changed .
        working-directory: packages/${{ matrix.package }}
      - run: dart analyze --fatal-infos
        working-directory: packages/${{ matrix.package }}
      - run: dart test
        working-directory: packages/${{ matrix.package }}
